version: "2"
services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - nginx_vhost:/etc/nginx/vhost.d:ro
      - nginx_html:/usr/share/nginx/html:ro
      - nginx_certs:/etc/nginx/certs:ro
    networks:
      - default
      - nginx
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  nginx-gen:
    build: docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    environment:
      ENABLE_IPV6: "true"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d:ro
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      DHPARAM_BITS: "4096"
    volumes:
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default

  dmarby:
    build: dmarby.se
    environment:
      VIRTUAL_HOST: "dmarby.se,www.dmarby.se"
      LETSENCRYPT_HOST: "dmarby.se,www.dmarby.se"
      LETSENCRYPT_EMAIL: "david@dmarby.se"
    networks:
      - nginx
    restart: always

  yokuso:
    build: yokuso
    environment:
      ACCESS_KEY_ID: ${SPACES_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SPACES_SECRET_ACCESS_KEY}
      SPACES_REGION: ams3
      SPACES_ENDPOINT: dmarby.ams3.digitaloceanspaces.com
      ROOT_REDIRECT: https://dmarby.se
      CLIENT_ACCESS_KEY_ID: ${YOKUSO_CLIENT_ACCESS_KEY_ID}
      CLIENT_SECRET_ACCESS_KEY: ${YOKUSO_CLIENT_SECRET_ACCESS_KEY}
      VIRTUAL_HOST: dump.dmarby.se
      LETSENCRYPT_HOST: "dump.dmarby.se"
      LETSENCRYPT_EMAIL: "david@dmarby.se"
    volumes:
      - yokuso_cache:/var/cache/nginx
    networks:
      - nginx
    restart: always

  klein:
    build: klein
    environment:
      KLEIN_STORAGE: spaces
      KLEIN_STORAGE_SPACES_REGION: ams3
      KLEIN_STORAGE_SPACES_ACCESS_KEY: ${SPACES_ACCESS_KEY_ID}
      KLEIN_STORAGE_SPACES_SECRET_KEY: ${SPACES_SECRET_ACCESS_KEY}
      KLEIN_STORAGE_SPACES_SPACE: dmarby
      KLEIN_STORAGE_SPACES_PATH: klein.json
      KLEIN_AUTH: key
      KLEIN_AUTH_KEY: ${KLEIN_API_KEY}
      KLEIN_ALIAS: alphanumeric
      KLEIN_ALIAS_ALPHANUMERIC_LENGTH: 8
      KLEIN_ALIAS_ALPHANUMERIC_ALPHA: "true"
      KLEIN_ALIAS_ALPHANUMERIC_NUM: "true"
      KLEIN_TEMPLATE: "404.html"
      KLEIN_LISTEN: "0.0.0.0:5556"
      KLEIN_URL: "https://dmar.by"
      KLEIN_ROOT: "https://dmarby.se"
      VIRTUAL_HOST: dmar.by
      LETSENCRYPT_HOST: "dmar.by"
      LETSENCRYPT_EMAIL: "david@dmarby.se"
    networks:
      - nginx
    expose:
      - "5556"
    restart: always

networks:
  default:
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
  nginx:

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:

  yokuso_cache:

